language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
install: "pip install ."
script:
  - "python setup.py test"
  - "if [[ $TRAVIS_PYTHON_VERSION = 2.7 ]]; then .travis/install_cython.sh; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION = 2.7 ]]; then .travis/test_cython_files.sh; fi"
