language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9
install: "pip install ."
script:
  - "python setup.py test"
  - "if [[ $TRAVIS_PYTHON_VERSION > 3.5 ]]; then scripts/install_cython.sh; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION > 3.5 ]]; then scripts/test_cython_files.sh; fi"
